##
# Makefile automatically generated by genmake 1.0, May-03-00
# genmake 1.0 by muquit@muquit.com, http://www.muquit.com/

PROGNAME= applehealth2csv
PROGNAME_WIN= $(PROGNAME).exe
PROGNAME_PI= $(PROGNAME)-raspberry-pi
PROGNAME_PI_JESSIE= $(PROGNAME)-raspberry-pi-jessie
DESTDIR=
VERSION=1.0.1
BUILD_OPTIONS = -ldflags "-X main.Version=$(VERSION)"
BINDIR= /usr/local/bin
MANPAGE= docs/applehealth2csv.1
MANDIR= /usr/local/share/man/man1
CP= /bin/cp -v
OS= $(shell go env GOOS)

all:
	@echo "- Compiling ${PROGNAME} ..."
	go build


$(PROGNAME) : native

linux: 
	@echo "- Building $(PROGNAME)_linux"
	@CGO_ENABLED=0 GOOS=linux go build -o $(PROGNAME)_linux
	/bin/ls -lt $(PROGNAME)_linux
	@echo ""

native:
	@echo "- Building $(PROGNAME)"
	@go build -o $(PROGNAME)
	/bin/ls -lt $(PROGNAME)
	@echo ""

windows:
	@echo "- Building $(PROGNAME_WIN) for Windows amd64"
	CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o $(PROGNAME_WIN)
	/bin/ls -lt $(PROGNAME_WIN)
	@echo ""

mac:
	@echo "- Building $(PROGNAME) for Mac amd64"
	CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o $(PROGNAME)_mac
	/bin/ls -lt $(PROGNAME)_mac
	@echo ""

pi: 
	@echo "- Building $(PROGNAME) for raspberry pi"
	GOOS=linux GOARCH=arm GOARM=7 go build -o $(PROGNAME_PI)
	/bin/ls -lt $(PROGNAME_PI)
	@echo ""

pijessie: 
	@echo "- Building $(PROGNAME) for raspberry pi jessie"
	GOARM=6 GOARCH=arm GOOS=linux go build -o $(PROGNAME_PI_JESSIE)
	/bin/ls -lt $(PROGNAME_PI_JESSIE)
	@echo ""


doc:
	@./scripts/mkdocs.sh
	@pandoc --standalone --to man README.md -o docs/applehealth2csv.1

install: install-bin

install-bin:
	$(CP) $(PROGNAME) $(BINDIR)
	$(CP) $(MANPAGE) $(MANDIR)

clean:
	/bin/rm -f $(PROGNAME) $(PROGNAME_WIN) $(PROGNAME)_$(OS) $(PROGNAME)_* *.bak \
		*.csv csv/* \
		$(PROGNAME)_linux $(PROGNAME)_mac
